In [1]:
import torch

In [2]:
tensor_a = torch.rand(3, 3)
tensor_b = torch.rand(3, 3)

In [ ]:
# matrix multiplication
result = torch.matmul(tensor_a, tensor_b)

In [4]:
result

tensor([[0.7027, 0.4375, 0.3778],
        [0.9086, 0.2788, 0.2812],
        [0.6577, 0.3388, 0.3013]])

In [6]:
tensor_a

tensor([[0.1324, 0.3017, 0.6725],
        [0.7557, 0.0304, 0.7657],
        [0.2375, 0.1678, 0.6987]])

In [7]:
tensor_b

tensor([[0.6773, 0.0756, 0.1214],
        [0.9618, 0.8468, 0.7102],
        [0.4801, 0.2558, 0.2193]])

In [8]:
if torch.cuda.is_available():
    print("GPU Available")
else:
    print("No GPU")

No GPU
