In [1]:
import torch

#### Creating Tensor

In [2]:
tensor_from_list = torch.tensor([1, 2, 3])
tensor_from_list

tensor([1, 2, 3])

In [3]:
import numpy as np
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = torch.tensor(np_array)

In [4]:
tensor_from_numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
tensor_zeros = torch.zeros(3, 3)
tensor_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
tensor_ones = torch.ones(3, 3)
tensor_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##### Random Tensor

In [ ]:
random_tensor = torch.rand(4, 4)
random_tensor

tensor([[0.6524, 0.7136, 0.6635, 0.1500],
        [0.7482, 0.2321, 0.8349, 0.4720],
        [0.8170, 0.7407, 0.2547, 0.4762],
        [0.3888, 0.4981, 0.7078, 0.2016]])

In [9]:
normal_tensor = torch.randn(4, 4)
normal_tensor

tensor([[-1.0847,  2.3136, -1.0794, -0.5078],
        [-0.7854,  0.3242,  2.1913,  0.6969],
        [ 1.5219, -0.4589,  0.0502,  0.2678],
        [ 0.6331, -0.2730,  0.3886, -0.5684]])

#### Datatype and Devices

In [10]:
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)

float_tensor

tensor([1., 2., 3.])

In [ ]:
gpu_tensor = torch.tensor([1, 2, 3], device='cuda')

#### Tensor Operation

In [11]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

sum_tensor = tensor_a + tensor_b

sum_tensor

tensor([5, 7, 9])

In [15]:
sub_tensor = tensor_a - tensor_b

sub_tensor

tensor([-3, -3, -3])

In [16]:
devide_tensor = tensor_a / tensor_b

devide_tensor

tensor([0.2500, 0.4000, 0.5000])

In [17]:
multiply_tensor = tensor_a * tensor_b

multiply_tensor

tensor([ 4, 10, 18])

In [14]:
tensor_aa = torch.tensor([[1, 2], [3, 4]])
tensor_bb = torch.tensor([[4, 5], [5, 6]])

result = torch.matmul(tensor_aa, tensor_bb)

result

tensor([[14, 17],
        [32, 39]])

#### Indexing & Slicing

In [19]:
tensor = torch.tensor([[1, 2], [3, 4]])
element = tensor[0][1]
element

tensor(2)

In [20]:
tensor2 = torch.tensor([[1, 2, 4], [4, 5, 6], [7, 8, 9]])

slic_tensor = tensor[:, 1:3]

slic_tensor

tensor([[2],
        [4]])

In [21]:
tensor3 = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(tensor3[[0, 2], :])

tensor([[1, 2],
        [5, 6]])


#### Broadcasting

In [22]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([2])

result2 = tensor1 + tensor2

result2

tensor([[3, 4],
        [5, 6]])

#### In-place operation

In [23]:
tensor0 = torch.tensor([1, 2, 4])
tensor0.add_(5)

tensor0

tensor([6, 7, 9])