In [1]:
import numpy as np

#### ReLu (Hidden Layer)

In [2]:
def relu(x):
    return np.maximum(0,x)

In [3]:
relu(10)

np.int64(10)

In [7]:
relu(np.array([9, 1, -1, 5]))

array([9, 1, 0, 5])

#### Leaky ReLu (Hidden Layer)

In [8]:
def leaky_ReLu(x, alpha=0.01):
    return np.where(x > 0, x, x * alpha)

In [9]:
leaky_ReLu(5)

array(5.)

In [10]:
leaky_ReLu(np.array([7, 2, -6, 5]))

array([ 7.  ,  2.  , -0.06,  5.  ])

#### ELU (Hidden Layer)

In [11]:
def elu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [12]:
elu(4)

array(4.)

In [14]:
elu(np.array([-1, 2, -5, 3]))

array([-0.00632121,  2.        , -0.00993262,  3.        ])

#### Sigmoid (OutPut Layer & BinaryClass Problem)

In [15]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [16]:
sigmoid(5)

np.float64(0.9933071490757153)

In [18]:
sigmoid((np.array([-1, 2, -6, 5])))

array([0.26894142, 0.88079708, 0.00247262, 0.99330715])

#### Softmax (OutPut Layer & MultiClass Problem)

In [22]:
def softmax(x):
    ex = np.exp(x - np.max(x))
    return ex / ex.sum()

In [23]:
proba = softmax((np.array([2, 1, 0.5])))
proba

array([0.62853172, 0.2312239 , 0.14024438])