In [3]:
import numpy as np

#### ReLu (Hidden Layer)

In [4]:
def relu(x):
    return np.maximum(0,x)

In [5]:
relu(10)

np.int64(10)

In [6]:
relu(np.array([9, 1, -1, 5]))

array([9, 1, 0, 5])

#### Leaky ReLu (Hidden Layer)

In [7]:
def leaky_ReLu(x, alpha=0.01):
    return np.where(x > 0, x, x * alpha)

In [8]:
leaky_ReLu(5)

array(5.)

In [9]:
leaky_ReLu(np.array([7, 2, -6, 5]))

array([ 7.  ,  2.  , -0.06,  5.  ])

#### ELU (Hidden Layer)

In [10]:
def elu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [11]:
elu(4)

array(4.)

In [12]:
elu(np.array([-1, 2, -5, 3]))

array([-0.00632121,  2.        , -0.00993262,  3.        ])

#### Sigmoid (OutPut Layer & BinaryClass Problem)

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [14]:
sigmoid(5)

np.float64(0.9933071490757153)

In [15]:
sigmoid((np.array([-1, 2, -6, 5])))

array([0.26894142, 0.88079708, 0.00247262, 0.99330715])

#### Softmax (OutPut Layer & MultiClass Problem)

In [16]:
def softmax(x):
    ex = np.exp(x - np.max(x))
    return ex / ex.sum()

In [17]:
proba = softmax((np.array([2, 1, 0.5])))
proba

array([0.62853172, 0.2312239 , 0.14024438])

#### Swish (Hidden Layer)

In [ ]:
def swish(x, beta=1.0):
    return x * sigmoid(beta * x)

In [19]:
swish(5)

np.float64(4.966535745378576)

In [20]:
swish(np.array([-1, 2, -5, 3]))

array([-0.26894142,  1.76159416, -0.03346425,  2.85772238])

#### Linear (Output Layer)

In [21]:
def linear(x):
    return x

In [22]:
linear(10)

10

#### Tanh (Hyperbolic Tangent)

In [23]:
def tanh(x):
    return np.tanh(x)

In [24]:
tanh(10)

np.float64(0.9999999958776927)

In [25]:
tanh(np.array([-1, 0, 1, 2]))

array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

In [26]:
def tanh2(x):
    result = (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
    return result

In [27]:
tanh2(10)

np.float64(0.9999999958776926)