In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
# Import Dataset
df = pd.read_csv('/content/drive/My Drive/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          608     Spain  Female  41.0   
2          3    15619304      Onio          502    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname',], axis=1)

In [8]:
x = df.drop('Exited', axis=1)
y = df['Exited']

In [9]:
x['Age'] = x['Age'].fillna(x['Age'].median())

In [10]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x['Gender'] = lb.fit_transform(x['Gender'])

lb2 = LabelEncoder()
x['Geography'] = lb2.fit_transform(x['Geography'])

x.head()

CreditScore  Geography  Gender   Age  Tenure    Balance  NumOfProducts  \
0          619          0       0  42.0       2       0.00              1   
1          608          2       0  41.0       1   83807.86              1   
2          502          0       0  42.0       8  159660.80              3   
3          699          0       0  39.0       1       0.00              2   
4          850          2       0  43.0       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [11]:
# Spliting the dataset into training set and test set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
len(x_test)

2000

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

### Decision Tree

In [14]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
pred = dt.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, pred)
acc = accuracy_score(y_test, pred)
print(cm)
print("\n",acc)

[[1354  241]
 [ 176  229]]

 0.7915


## ANN

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [17]:
# Initialising the ANN

model = Sequential()

# Input Layer
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=10))

# Second Hidden Layer
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

# Third Hidden Layer
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

# Output Layer
model.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 6)              │            66 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 157 (628.00 B)

 Trainable params: 157 (628.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=10, epochs=50)

Epoch 1/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7960 - loss: 0.4843
Epoch 2/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7960 - loss: 0.4371
Epoch 3/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.4311
Epoch 4/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8161 - loss: 0.4261
Epoch 5/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8242 - loss: 0.4230
Epoch 6/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8270 - loss: 0.4212
Epoch 7/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8289 - loss: 0.4195
Epoch 8/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8300 - loss: 0.4172
Epoch 9/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8298 - loss: 0.4164
Epoch 10/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8325 - loss: 0.4151
Epoch 11/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8316 - loss: 0.4144
Epoch 12/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

In [20]:
y_pred_ann = model.predict(x_test)
y_pred_ann = (y_pred_ann > 0.5)

cm2 = confusion_matrix(y_test, y_pred_ann)
acc2 = accuracy_score(y_test, y_pred_ann)
print(cm2)
print("\n",acc2)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
[[1548   47]
 [ 276  129]]

 0.8385


In [21]:
# Predicting a single new observation

new_prediction = model.predict(sc.transform(np.array([[600, 40, 3, 60000, 2, 1, 1, 50000, 0, 0]])))
new_prediction = (new_prediction > 0.5)
new_prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[False]])

In [23]:
#Importing libraries for k-folds
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
  model = Sequential()
  model.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=10))
  model.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
  model.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
  model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return model

classifire = KerasClassifier(model=build_classifier, batch_size=10, epochs=10)


In [24]:
accuracies = cross_val_score(estimator=classifire, X=x_train, y=y_train, cv=5, n_jobs=-1)

mean1 = accuracies.mean()

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [25]:
#Improvising the ANN - Hyper parameter optimization

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense


def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(model = build_classifier)

parameters = {'batch_size': [10, 20],
              'epochs': [5, 6]}


grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', n_jobs = -1, cv = 5)
grid_search = grid_search.fit(x_train, y_train)
grid_search.best_params_
grid_search.best_score_

AttributeError: 'super' object has no attribute '__sklearn_tags__'